# Generated by Django 4.1.5 on 2024-08-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.TextField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
